### ISSUE TITLE
Overwriting default templates

### ISSUE THREAD

**Issue by studio4** [mejta/wp-plugin-boilerplate#2]
Hello Daniel,

I realise from your previous comments that this isn't a public project and any help you can give is entirely without warranty. I certainly don't want to be a nuisance. I'd really like to use the plugin I'm just missing one piece of the puzzle:

I'm struggling to overwrite the default theme templates with this plugin - perhaps it's outside of the scope or perhaps I'm doing something wrong. I was hoping to create a new template for a custom post type (defined in the plugin). 

I've tried various iterations of this:
```
    add_filter('single_template', function ($template) {
        global $post;
        if ($post->post_type == "product" && $template !== locate_template(array("product.php"))){
            return plugin_dir_path( __FILE__ ) . "product.blade.php";
        }
        return $template;
    });
```

The error I'm getting in the PHP logs is 

> Got error 'PHP message: PHP Fatal error: Uncaught InvalidArgumentException: View [.var.www.vhosts.xxx.com.wp-content.plugins.wp-current-rms.app.views.product.blade.php] not found. in /var/www/vhosts/xxx.com/wp-content/plugins/wp-current-rms/vendor/illuminate/view/FileViewFinder.php:137

I can see you have a few example functions of how to overwrite content from the_content() which is great - I just need to be able to replace (or actually create) a new template structure and pass blade variables to it. Is this possible?

I'm just not all that sure how to work around this issue - is there any way you could steer me in the right direction?

Many thanks
Andy

**Comment by mejta** [comment]
Hi Andy,

I would do something like this:
https://github.com/roots/sage/blob/master/app/filters.php#L63

```php
add_filter('single_template', function ($template) {
        global $post;
        if ($post->post_type == "product" && $template !== locate_template(array("product.php"))){
            echo plugin_dir_path( __FILE__ ) . "product.blade.php";
        }
        return get_stylesheet_directory().'/index.php';
    });
```

**Comment by studio4** [comment]
Hello Daniel,

Apologies for not coming back to you. The code above didn't work (for me) and unfortunately I am running tight on time to work out why so I am incorporating some of the changes needed into the theme itself. Once I have time I'll feed back some working code to you if that would be helpful.

Thanks
Andy

**Comment by mejta** [comment]
Thanks, Andy. Feel free to open a pull request.
